export function getMathBoardElements(root = document) {
  const query = (selector) => root.querySelector(selector);
  const queryAll = (selector) => [...root.querySelectorAll(selector)];

  return {
    axisLabels: query("#mathboard-axis-labels"),
    axisNumbersButton: query("#mathboard-axis-numbers"),
    axisSizeInput: query("#mathboard-axis-size"),
    axisSizeOutput: query("#mathboard-axis-size-output"),
    board: query("#mathboard-board"),
    canvas: query("#mathboard-canvas"),
    canvasTabs: query("#mathboard-canvas-tabs"),
    clearButton: query("#mathboard-clear"),
    colorButtons: queryAll("[data-color]"),
    deleteCanvasButton: query("#mathboard-canvas-delete"),
    duplicateCanvasButton: query("#mathboard-canvas-duplicate"),
    eraserPreview: query("#mathboard-eraser-preview"),
    exportProjectButton: query("#mathboard-project-export"),
    fullscreenButton: query("#mathboard-fullscreen"),
    fullscreenClearButton: query("#mathboard-fullscreen-clear"),
    fullscreenHistoryButton: query("#mathboard-fullscreen-history"),
    fullscreenRedoButton: query("#mathboard-fullscreen-redo"),
    fullscreenUndoButton: query("#mathboard-fullscreen-undo"),
    gridButtons: queryAll("[data-grid]"),
    historyCloseButton: query("#mathboard-history-close"),
    historyEndButton: query("#mathboard-history-end"),
    historyOutput: query("#mathboard-history-output"),
    historyRange: query("#mathboard-history-range"),
    historyScrubber: query("#mathboard-history-scrubber"),
    historyStartButton: query("#mathboard-history-start"),
    historyToggleButton: query("#mathboard-history-toggle"),
    importProjectButton: query("#mathboard-project-import"),
    newCanvasButton: query("#mathboard-canvas-new"),
    newProjectButton: query("#mathboard-project-new"),
    panelSections: queryAll("[data-panel-section]"),
    panelTabButtons: queryAll("[data-panel-tab]"),
    panelToggleButton: query("#mathboard-panel-toggle"),
    pdfButton: query("#mathboard-pdf"),
    projectFileInput: query("#mathboard-project-file"),
    projectMenu: query("#mathboard-project-menu"),
    redoButton: query("#mathboard-redo"),
    renameCanvasButton: query("#mathboard-canvas-rename"),
    renameCanvasCancel: query("#mathboard-rename-cancel"),
    renameCanvasDialog: query("#mathboard-rename-dialog"),
    renameCanvasForm: query("#mathboard-rename-form"),
    renameCanvasInput: query("#mathboard-canvas-name"),
    saveButton: query("#mathboard-save"),
    saveStatus: query("#mathboard-save-status"),
    shareProjectButton: query("#mathboard-project-share"),
    sizeInput: query("#mathboard-size"),
    sizeLabel: query("#mathboard-size-label"),
    sizeOutput: query("#mathboard-size-output"),
    smoothingButton: query("#mathboard-smoothing"),
    status: query("#mathboard-status"),
    toolButtons: queryAll("[data-tool]"),
    undoButton: query("#mathboard-undo"),
    zoomInButton: query("#mathboard-zoom-in"),
    zoomOutButton: query("#mathboard-zoom-out"),
    zoomResetButton: query("#mathboard-zoom-reset"),
    zoomSelection: query("#mathboard-zoom-selection"),
  };
}
